
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PAREND = 28;
  public static final int MAQ = 43;
  public static final int POW = 38;
  public static final int WHEN = 24;
  public static final int SHOW = 16;
  public static final int STRING_LITERAL = 64;
  public static final int FUNCTION = 5;
  public static final int CHAR = 57;
  public static final int CHAR_LITERAL = 63;
  public static final int UMINUS = 3;
  public static final int SEMI = 2;
  public static final int BRACKETI = 32;
  public static final int INT = 54;
  public static final int MINUS = 35;
  public static final int FOR = 13;
  public static final int BRACKETD = 33;
  public static final int NOT = 53;
  public static final int AND = 51;
  public static final int ENDL = 31;
  public static final int BLOQUE_CER = 26;
  public static final int SEMICOLON = 30;
  public static final int IQ = 41;
  public static final int DECIDE = 18;
  public static final int COAL = 8;
  public static final int OR = 52;
  public static final int GET = 17;
  public static final int NAVIDAD = 9;
  public static final int INC = 48;
  public static final int DIV = 37;
  public static final int MAIQ = 45;
  public static final int LOOP = 22;
  public static final int PLUS = 34;
  public static final int EXIT = 23;
  public static final int IF = 10;
  public static final int OF = 19;
  public static final int BOOLEAN = 56;
  public static final int ABSTRACT = 4;
  public static final int EOF = 0;
  public static final int RETURN = 6;
  public static final int error = 1;
  public static final int COMA = 29;
  public static final int MOD = 39;
  public static final int DIVINT = 40;
  public static final int BLOQUE_ABI = 25;
  public static final int BREAK = 21;
  public static final int WORLD = 14;
  public static final int TIMES = 36;
  public static final int ARROW = 50;
  public static final int MEQ = 44;
  public static final int ELSE = 11;
  public static final int DIFQ = 47;
  public static final int WHILE = 12;
  public static final int FLOAT = 55;
  public static final int END = 20;
  public static final int STRING = 58;
  public static final int LOCAL = 15;
  public static final int DEC = 49;
  public static final int FLOAT_LITERAL = 61;
  public static final int IQIQ = 42;
  public static final int MEIQ = 46;
  public static final int PARENI = 27;
  public static final int GIFT = 7;
  public static final int BOOL_LITERAL = 62;
  public static final int INTEGER_LITERAL = 60;
  public static final int IDENTIFIER = 59;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMI",
  "UMINUS",
  "ABSTRACT",
  "FUNCTION",
  "RETURN",
  "GIFT",
  "COAL",
  "NAVIDAD",
  "IF",
  "ELSE",
  "WHILE",
  "FOR",
  "WORLD",
  "LOCAL",
  "SHOW",
  "GET",
  "DECIDE",
  "OF",
  "END",
  "BREAK",
  "LOOP",
  "EXIT",
  "WHEN",
  "BLOQUE_ABI",
  "BLOQUE_CER",
  "PARENI",
  "PAREND",
  "COMA",
  "SEMICOLON",
  "ENDL",
  "BRACKETI",
  "BRACKETD",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIV",
  "POW",
  "MOD",
  "DIVINT",
  "IQ",
  "IQIQ",
  "MAQ",
  "MEQ",
  "MAIQ",
  "MEIQ",
  "DIFQ",
  "INC",
  "DEC",
  "ARROW",
  "AND",
  "OR",
  "NOT",
  "INT",
  "FLOAT",
  "BOOLEAN",
  "CHAR",
  "STRING",
  "IDENTIFIER",
  "INTEGER_LITERAL",
  "FLOAT_LITERAL",
  "BOOL_LITERAL",
  "CHAR_LITERAL",
  "STRING_LITERAL"
  };
}

