// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: lexer.jflex

/* JFlex example: partial Java language lexer specification */
   import java_cup.runtime.*;

   /* This class is a simple example lexer */

@SuppressWarnings("fallthrough")
class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1, 1
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\2\u0100\1\u0200\1\u0300\33\u0100\1\u0400\267\u0100\10\u0500"+
    "\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\4\1\5\22\0\1\1"+
    "\1\6\1\7\2\0\1\10\1\0\1\11\2\0\1\12"+
    "\1\13\1\14\1\15\1\16\1\17\1\20\11\21\1\0"+
    "\1\22\1\23\1\24\1\25\1\26\1\27\32\30\1\31"+
    "\1\32\1\33\1\34\1\35\1\0\1\36\1\37\1\40"+
    "\1\41\1\42\1\43\1\44\1\45\1\46\1\30\1\47"+
    "\1\50\1\30\1\51\1\52\1\53\1\30\1\54\1\55"+
    "\1\56\1\57\1\60\1\61\1\62\2\30\1\0\1\63"+
    "\1\0\1\64\6\0\1\3\33\0\1\65\35\0\1\66"+
    "\u01e3\0\1\67\251\0\1\70\6\0\1\71\323\0\2\3"+
    "\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1536];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\2\2\1\3\1\4\1\5\1\1\1\6"+
    "\1\7\1\10\1\11\1\12\2\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\25\17\22"+
    "\1\2\1\26\1\27\1\30\1\31\1\1\1\32\1\33"+
    "\1\0\1\34\2\0\1\35\1\36\1\37\1\40\1\0"+
    "\1\41\1\42\1\43\17\22\1\44\3\22\1\45\6\22"+
    "\1\0\1\46\1\47\1\50\1\51\1\52\1\53\1\54"+
    "\7\22\1\55\3\22\1\56\1\22\1\57\1\22\1\60"+
    "\15\22\1\61\1\62\1\22\1\63\1\64\1\65\2\22"+
    "\1\66\1\22\1\67\2\22\1\70\1\22\1\71\1\72"+
    "\4\22\1\73\1\22\1\74\1\22\1\75\3\22\1\76"+
    "\1\77\2\22\1\100\2\22\1\101\1\102\1\22\1\103"+
    "\1\22\1\104\1\105\1\106";

  private static int [] zzUnpackAction() {
    int [] result = new int[168];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\72\0\164\0\164\0\256\0\350\0\164\0\164"+
    "\0\u0122\0\164\0\u015c\0\164\0\u0196\0\u01d0\0\u020a\0\u0244"+
    "\0\164\0\u027e\0\u02b8\0\u02f2\0\164\0\164\0\u032c\0\164"+
    "\0\164\0\164\0\u0366\0\u03a0\0\u03da\0\u0414\0\u044e\0\u0488"+
    "\0\u04c2\0\u04fc\0\u0536\0\u0570\0\u05aa\0\u05e4\0\u061e\0\u0658"+
    "\0\u0692\0\u06cc\0\164\0\164\0\164\0\164\0\u0706\0\u0740"+
    "\0\164\0\u077a\0\164\0\u07b4\0\u07ee\0\164\0\164\0\164"+
    "\0\164\0\u0828\0\164\0\164\0\164\0\u0862\0\u089c\0\u08d6"+
    "\0\u0910\0\u094a\0\u0984\0\u09be\0\u09f8\0\u0a32\0\u0a6c\0\u0aa6"+
    "\0\u0ae0\0\u0b1a\0\u0b54\0\u0b8e\0\u032c\0\u0bc8\0\u0c02\0\u0c3c"+
    "\0\u032c\0\u0c76\0\u0cb0\0\u0cea\0\u0d24\0\u0d5e\0\u0d98\0\u0706"+
    "\0\164\0\164\0\164\0\164\0\164\0\164\0\u0828\0\u0dd2"+
    "\0\u0e0c\0\u0e46\0\u0e80\0\u0eba\0\u0ef4\0\u0f2e\0\u0f68\0\u0fa2"+
    "\0\u0fdc\0\u1016\0\u032c\0\u1050\0\u032c\0\u108a\0\u032c\0\u10c4"+
    "\0\u10fe\0\u1138\0\u1172\0\u11ac\0\u11e6\0\u1220\0\u125a\0\u1294"+
    "\0\u12ce\0\u1308\0\u1342\0\u137c\0\u032c\0\u032c\0\u13b6\0\u032c"+
    "\0\u032c\0\u032c\0\u13f0\0\u142a\0\u032c\0\u1464\0\u032c\0\u149e"+
    "\0\u14d8\0\u032c\0\u1512\0\u032c\0\u032c\0\u154c\0\u1586\0\u15c0"+
    "\0\u15fa\0\u032c\0\u1634\0\u032c\0\u166e\0\u032c\0\u16a8\0\u16e2"+
    "\0\u171c\0\u032c\0\u032c\0\u1756\0\u1790\0\u032c\0\u17ca\0\u1804"+
    "\0\u032c\0\u032c\0\u183e\0\u032c\0\u1878\0\u032c\0\u032c\0\u032c";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[168];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\2\4\1\0\1\4\1\5\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\3\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\1\26\1\27"+
    "\1\30\1\3\1\31\1\32\1\3\1\33\1\34\1\35"+
    "\1\36\1\37\1\40\1\41\1\27\1\42\1\27\1\43"+
    "\1\44\1\45\1\27\1\46\1\47\1\50\2\27\1\51"+
    "\1\27\1\52\1\53\1\54\1\55\1\56\1\3\1\57"+
    "\2\60\1\0\2\60\1\0\1\60\1\61\22\60\1\62"+
    "\37\60\74\0\1\4\113\0\1\63\45\0\11\64\1\0"+
    "\20\64\1\65\37\64\13\0\1\66\73\0\1\67\2\0"+
    "\1\17\1\20\3\0\1\70\63\0\1\71\70\0\1\72"+
    "\71\0\1\72\1\0\2\20\74\0\1\73\71\0\1\74"+
    "\71\0\1\75\65\0\2\27\6\0\1\27\4\0\26\27"+
    "\27\0\2\27\6\0\1\27\4\0\2\27\1\76\23\27"+
    "\27\0\2\27\6\0\1\27\4\0\15\27\1\77\1\27"+
    "\1\100\6\27\27\0\2\27\6\0\1\27\4\0\10\27"+
    "\1\101\4\27\1\102\10\27\27\0\2\27\6\0\1\27"+
    "\4\0\5\27\1\103\20\27\27\0\2\27\6\0\1\27"+
    "\4\0\13\27\1\104\1\105\10\27\1\106\27\0\2\27"+
    "\6\0\1\27\4\0\1\27\1\107\11\27\1\110\1\27"+
    "\1\111\4\27\1\112\3\27\27\0\2\27\6\0\1\27"+
    "\4\0\5\27\1\113\3\27\1\114\14\27\27\0\2\27"+
    "\6\0\1\27\4\0\6\27\1\115\5\27\1\116\11\27"+
    "\27\0\2\27\6\0\1\27\4\0\15\27\1\117\10\27"+
    "\27\0\2\27\6\0\1\27\4\0\1\27\1\120\24\27"+
    "\27\0\2\27\6\0\1\27\4\0\6\27\1\121\17\27"+
    "\27\0\2\27\6\0\1\27\4\0\5\27\1\122\20\27"+
    "\27\0\2\27\6\0\1\27\4\0\10\27\1\123\10\27"+
    "\1\124\4\27\27\0\2\27\6\0\1\27\4\0\17\27"+
    "\1\125\6\27\27\0\2\27\6\0\1\27\4\0\10\27"+
    "\1\126\4\27\1\127\10\27\7\0\2\52\1\4\2\52"+
    "\1\5\64\52\70\130\1\4\1\130\2\60\1\0\2\60"+
    "\1\0\1\60\1\0\22\60\1\0\37\60\7\0\1\131"+
    "\22\0\1\132\16\0\1\133\2\0\1\134\1\0\1\135"+
    "\24\0\1\136\60\0\2\64\4\0\64\64\20\0\2\137"+
    "\70\0\2\27\6\0\1\27\4\0\20\27\1\140\5\27"+
    "\27\0\2\27\6\0\1\27\4\0\15\27\1\141\10\27"+
    "\27\0\2\27\6\0\1\27\4\0\5\27\1\142\20\27"+
    "\27\0\2\27\6\0\1\27\4\0\1\27\1\143\24\27"+
    "\27\0\2\27\6\0\1\27\4\0\1\27\1\144\24\27"+
    "\27\0\2\27\6\0\1\27\4\0\3\27\1\145\22\27"+
    "\27\0\2\27\6\0\1\27\4\0\20\27\1\146\5\27"+
    "\27\0\2\27\6\0\1\27\4\0\4\27\1\147\21\27"+
    "\27\0\2\27\6\0\1\27\4\0\11\27\1\150\14\27"+
    "\27\0\2\27\6\0\1\27\4\0\13\27\1\151\12\27"+
    "\27\0\2\27\6\0\1\27\4\0\15\27\1\152\10\27"+
    "\27\0\2\27\6\0\1\27\4\0\17\27\1\153\6\27"+
    "\27\0\2\27\6\0\1\27\4\0\14\27\1\154\11\27"+
    "\27\0\2\27\6\0\1\27\4\0\21\27\1\155\4\27"+
    "\27\0\2\27\6\0\1\27\4\0\6\27\1\156\17\27"+
    "\27\0\2\27\6\0\1\27\4\0\21\27\1\157\4\27"+
    "\27\0\2\27\6\0\1\27\4\0\3\27\1\160\11\27"+
    "\1\161\10\27\27\0\2\27\6\0\1\27\4\0\23\27"+
    "\1\162\2\27\27\0\2\27\6\0\1\27\4\0\21\27"+
    "\1\163\4\27\27\0\2\27\6\0\1\27\4\0\15\27"+
    "\1\164\10\27\27\0\2\27\6\0\1\27\4\0\17\27"+
    "\1\165\6\27\27\0\2\27\6\0\1\27\4\0\22\27"+
    "\1\166\3\27\27\0\2\27\6\0\1\27\4\0\5\27"+
    "\1\167\3\27\1\170\14\27\27\0\2\27\6\0\1\27"+
    "\4\0\17\27\1\171\6\27\27\0\2\27\6\0\1\27"+
    "\4\0\21\27\1\172\4\27\27\0\2\27\6\0\1\27"+
    "\4\0\13\27\1\173\12\27\27\0\2\27\6\0\1\27"+
    "\4\0\1\27\1\174\24\27\27\0\2\27\6\0\1\27"+
    "\4\0\17\27\1\175\6\27\27\0\2\27\6\0\1\27"+
    "\4\0\13\27\1\176\12\27\27\0\2\27\6\0\1\27"+
    "\4\0\11\27\1\177\14\27\27\0\2\27\6\0\1\27"+
    "\4\0\5\27\1\200\20\27\27\0\2\27\6\0\1\27"+
    "\4\0\13\27\1\201\12\27\27\0\2\27\6\0\1\27"+
    "\4\0\21\27\1\202\4\27\27\0\2\27\6\0\1\27"+
    "\4\0\20\27\1\166\5\27\27\0\2\27\6\0\1\27"+
    "\4\0\1\27\1\203\24\27\27\0\2\27\6\0\1\27"+
    "\4\0\3\27\1\204\22\27\27\0\2\27\6\0\1\27"+
    "\4\0\21\27\1\205\4\27\27\0\2\27\6\0\1\27"+
    "\4\0\1\27\1\206\24\27\27\0\2\27\6\0\1\27"+
    "\4\0\16\27\1\207\7\27\27\0\2\27\6\0\1\27"+
    "\4\0\11\27\1\210\14\27\27\0\2\27\6\0\1\27"+
    "\4\0\22\27\1\211\3\27\27\0\2\27\6\0\1\27"+
    "\4\0\24\27\1\212\1\27\27\0\2\27\6\0\1\27"+
    "\4\0\11\27\1\213\14\27\27\0\2\27\6\0\1\27"+
    "\4\0\5\27\1\214\20\27\27\0\2\27\6\0\1\27"+
    "\4\0\14\27\1\215\11\27\27\0\2\27\6\0\1\27"+
    "\4\0\13\27\1\216\12\27\27\0\2\27\6\0\1\27"+
    "\4\0\13\27\1\217\12\27\27\0\2\27\6\0\1\27"+
    "\4\0\17\27\1\220\6\27\27\0\2\27\6\0\1\27"+
    "\4\0\5\27\1\221\20\27\27\0\2\27\6\0\1\27"+
    "\4\0\12\27\1\222\13\27\27\0\2\27\6\0\1\27"+
    "\4\0\4\27\1\223\21\27\27\0\2\27\6\0\1\27"+
    "\4\0\21\27\1\224\4\27\27\0\2\27\6\0\1\27"+
    "\4\0\21\27\1\225\4\27\27\0\2\27\6\0\1\27"+
    "\4\0\13\27\1\226\12\27\27\0\2\27\6\0\1\27"+
    "\4\0\4\27\1\227\21\27\27\0\2\27\6\0\1\27"+
    "\4\0\17\27\1\230\6\27\27\0\2\27\6\0\1\27"+
    "\4\0\14\27\1\231\11\27\27\0\2\27\6\0\1\27"+
    "\4\0\5\27\1\232\20\27\27\0\2\27\6\0\1\27"+
    "\4\0\4\27\1\233\21\27\27\0\2\27\6\0\1\27"+
    "\4\0\1\27\1\234\24\27\27\0\2\27\6\0\1\27"+
    "\4\0\1\27\1\235\24\27\27\0\2\27\6\0\1\27"+
    "\4\0\5\27\1\236\20\27\27\0\2\27\6\0\1\27"+
    "\4\0\11\27\1\237\14\27\27\0\2\27\6\0\1\27"+
    "\4\0\1\27\1\240\24\27\27\0\2\27\6\0\1\27"+
    "\4\0\14\27\1\241\11\27\27\0\2\27\6\0\1\27"+
    "\4\0\7\27\1\242\16\27\27\0\2\27\6\0\1\27"+
    "\4\0\3\27\1\243\22\27\27\0\2\27\6\0\1\27"+
    "\4\0\14\27\1\244\11\27\27\0\2\27\6\0\1\27"+
    "\4\0\15\27\1\245\10\27\27\0\2\27\6\0\1\27"+
    "\4\0\4\27\1\246\21\27\27\0\2\27\6\0\1\27"+
    "\4\0\21\27\1\247\4\27\27\0\2\27\6\0\1\27"+
    "\4\0\14\27\1\250\11\27\7\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[6322];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\2\11\2\1\2\11\1\1\1\11\1\1\1\11"+
    "\4\1\1\11\3\1\2\11\1\1\3\11\20\1\4\11"+
    "\2\1\1\11\1\0\1\11\2\0\4\11\1\0\3\11"+
    "\32\1\1\0\6\11\112\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[168];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
  StringBuffer string = new StringBuffer();
  private Symbol symbol(int type) {
    return new Symbol(type, yyline + 1, yycolumn + 1, yytext());
  }

  private Symbol symbol(int type, Object value) {
    return new Symbol(type, yyline + 1, yycolumn + 1, value);
  }

  private void reportError(String msg) {
    System.err.println(msg);
  }



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { // Reporta el error
        System.err.println(
            "Error léxico: caracter ilegal '" + yytext() +
            "' en línea " + (yyline + 1) +
            ", columna " + (yycolumn + 1)
        );
            }
          // fall through
          case 71: break;
          case 2:
            { /* ignore */
            }
          // fall through
          case 72: break;
          case 3:
            { return symbol(sym.BLOQUE_CER);
            }
          // fall through
          case 73: break;
          case 4:
            { string.setLength(0);yybegin(STRING);
            }
          // fall through
          case 74: break;
          case 5:
            { return symbol(sym.MOD);
            }
          // fall through
          case 75: break;
          case 6:
            { return symbol(sym.TIMES);
            }
          // fall through
          case 76: break;
          case 7:
            { return symbol(sym.PLUS);
            }
          // fall through
          case 77: break;
          case 8:
            { return symbol(sym.COMA);
            }
          // fall through
          case 78: break;
          case 9:
            { return symbol(sym.MINUS);
            }
          // fall through
          case 79: break;
          case 10:
            { return symbol(sym.DIV);
            }
          // fall through
          case 80: break;
          case 11:
            { return symbol(sym.INTEGER_LITERAL);
            }
          // fall through
          case 81: break;
          case 12:
            { return symbol(sym.SEMICOLON);
            }
          // fall through
          case 82: break;
          case 13:
            { return symbol(sym.MEQ);
            }
          // fall through
          case 83: break;
          case 14:
            { return symbol(sym.IQ);
            }
          // fall through
          case 84: break;
          case 15:
            { return symbol(sym.MAQ);
            }
          // fall through
          case 85: break;
          case 16:
            { return symbol(sym.PAREND);
            }
          // fall through
          case 86: break;
          case 17:
            { return symbol(sym.AND);
            }
          // fall through
          case 87: break;
          case 18:
            { return symbol(sym.IDENTIFIER, yytext());
            }
          // fall through
          case 88: break;
          case 19:
            { return symbol(sym.BRACKETI);
            }
          // fall through
          case 89: break;
          case 20:
            { return symbol(sym.BRACKETD);
            }
          // fall through
          case 90: break;
          case 21:
            { return symbol(sym.POW);
            }
          // fall through
          case 91: break;
          case 22:
            { return symbol(sym.OR);
            }
          // fall through
          case 92: break;
          case 23:
            { return symbol(sym.BLOQUE_ABI);
            }
          // fall through
          case 93: break;
          case 24:
            { return symbol(sym.PARENI);
            }
          // fall through
          case 94: break;
          case 25:
            { return symbol(sym.NOT);
            }
          // fall through
          case 95: break;
          case 26:
            { string.append(yytext());
            }
          // fall through
          case 96: break;
          case 27:
            { yybegin(YYINITIAL);
            return symbol(sym.STRING_LITERAL, string.toString());
            }
          // fall through
          case 97: break;
          case 28:
            { return symbol(sym.DIFQ);
            }
          // fall through
          case 98: break;
          case 29:
            { return symbol(sym.INC);
            }
          // fall through
          case 99: break;
          case 30:
            { return symbol(sym.DEC);
            }
          // fall through
          case 100: break;
          case 31:
            { return symbol(sym.ARROW);
            }
          // fall through
          case 101: break;
          case 32:
            { return symbol(sym.DIVINT);
            }
          // fall through
          case 102: break;
          case 33:
            { return symbol(sym.MEIQ);
            }
          // fall through
          case 103: break;
          case 34:
            { return symbol(sym.IQIQ);
            }
          // fall through
          case 104: break;
          case 35:
            { return symbol(sym.MAIQ);
            }
          // fall through
          case 105: break;
          case 36:
            { return symbol(sym.IF);
            }
          // fall through
          case 106: break;
          case 37:
            { return symbol(sym.OF);
            }
          // fall through
          case 107: break;
          case 38:
            { string.append('\"');
            }
          // fall through
          case 108: break;
          case 39:
            { string.append('\\');
            }
          // fall through
          case 109: break;
          case 40:
            { string.append('\n');
            }
          // fall through
          case 110: break;
          case 41:
            { string.append('\r');
            }
          // fall through
          case 111: break;
          case 42:
            { string.append('\t');
            }
          // fall through
          case 112: break;
          case 43:
            { return symbol(sym.CHAR_LITERAL, yytext());
            }
          // fall through
          case 113: break;
          case 44:
            { return symbol(sym.FLOAT_LITERAL);
            }
          // fall through
          case 114: break;
          case 45:
            { return symbol(sym.END);
            }
          // fall through
          case 115: break;
          case 46:
            { return symbol(sym.FOR);
            }
          // fall through
          case 116: break;
          case 47:
            { return symbol(sym.GET);
            }
          // fall through
          case 117: break;
          case 48:
            { return symbol(sym.INT);
            }
          // fall through
          case 118: break;
          case 49:
            { return symbol(sym.CHAR);
            }
          // fall through
          case 119: break;
          case 50:
            { return symbol(sym.COAL);
            }
          // fall through
          case 120: break;
          case 51:
            { return symbol(sym.ELSE);
            }
          // fall through
          case 121: break;
          case 52:
            { return symbol(sym.ENDL);
            }
          // fall through
          case 122: break;
          case 53:
            { return symbol(sym.EXIT);
            }
          // fall through
          case 123: break;
          case 54:
            { return symbol(sym.GIFT);
            }
          // fall through
          case 124: break;
          case 55:
            { return symbol(sym.LOOP);
            }
          // fall through
          case 125: break;
          case 56:
            { return symbol(sym.SHOW);
            }
          // fall through
          case 126: break;
          case 57:
            { return symbol(sym.BOOL_LITERAL);
            }
          // fall through
          case 127: break;
          case 58:
            { return symbol(sym.WHEN);
            }
          // fall through
          case 128: break;
          case 59:
            { return symbol(sym.BREAK);
            }
          // fall through
          case 129: break;
          case 60:
            { return symbol(sym.FLOAT);
            }
          // fall through
          case 130: break;
          case 61:
            { return symbol(sym.LOCAL);
            }
          // fall through
          case 131: break;
          case 62:
            { return symbol(sym.WHILE);
            }
          // fall through
          case 132: break;
          case 63:
            { return symbol(sym.WORLD);
            }
          // fall through
          case 133: break;
          case 64:
            { return symbol(sym.DECIDE);
            }
          // fall through
          case 134: break;
          case 65:
            { return symbol(sym.RETURN);
            }
          // fall through
          case 135: break;
          case 66:
            { return symbol(sym.STRING);
            }
          // fall through
          case 136: break;
          case 67:
            { return symbol(sym.BOOLEAN);
            }
          // fall through
          case 137: break;
          case 68:
            { return symbol(sym.NAVIDAD);
            }
          // fall through
          case 138: break;
          case 69:
            { return symbol(sym.ABSTRACT);
            }
          // fall through
          case 139: break;
          case 70:
            { return symbol(sym.FUNCTION);
            }
          // fall through
          case 140: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
